railsimplementation/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :movie_likes
  devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

railsimplementation/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railsimplementation/app/models/movie_like.rb
class MovieLike < ApplicationRecord
end

railsimplementation/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

railsimplementation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railsimplementation/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to movie_likes_path
    else
      redirect_to new_user_session_path
    end
  end
end

railsimplementation/app/controllers/movie_likes_controller.rb
class MovieLikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie_like, only: [:show, :edit, :update, :destroy]

  # GET /movie_likes
  # GET /movie_likes.json
  def index
    @movie_likes = MovieLike.all
  end

  # GET /movie_likes/1
  # GET /movie_likes/1.json
  def show
  end

  # GET /movie_likes/new
  def new
    @movie_like = MovieLike.new
  end

  # GET /movie_likes/1/edit
  def edit
  end

  # POST /movie_likes
  # POST /movie_likes.json
  def create
    @movie_like = MovieLike.new(movie_like_params)

    respond_to do |format|
      if @movie_like.save
        format.html { redirect_to @movie_like, notice: 'Movie like was successfully created.' }
        format.json { render :show, status: :created, location: @movie_like }
      else
        format.html { render :new }
        format.json { render json: @movie_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_likes/1
  # PATCH/PUT /movie_likes/1.json
  def update
    respond_to do |format|
      if @movie_like.update(movie_like_params)
        format.html { redirect_to @movie_like, notice: 'Movie like was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_like }
      else
        format.html { render :edit }
        format.json { render json: @movie_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_likes/1
  # DELETE /movie_likes/1.json
  def destroy
    @movie_like.destroy
    respond_to do |format|
      format.html { redirect_to movie_likes_url, notice: 'Movie like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_like
      @movie_like = MovieLike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_like_params
      params.require(:movie_like).permit(:movie, :like)
    end
end

railsimplementation/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

railsimplementation/app/helpers/application_helper.rb
module ApplicationHelper
end

railsimplementation/app/helpers/home_helper.rb
module HomeHelper
end

railsimplementation/app/helpers/movie_likes_helper.rb
module MovieLikesHelper
end

railsimplementation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/danielgindi-jquery-backstretch/2.1.13/jquery.backstretch.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Movie Match</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Catalog</a></li>
            <li><a href="#">About</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <a>Welcome <%= current_user.name %></a></li><li><%=link_to "Sign Out", destroy_user_session_path, :method => 'delete' %>
              <%else%>
                <%= link_to('Login', new_user_session_path) %></li>
                <li><%= link_to('Register', new_user_registration_path) %>
              <%end%>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
    <%= render "/backgroundSlider" %>
    
  </body>
</html>

railsimplementation/app/views/movie_likes/_form.html.erb
<%= form_for(movie_like) do |f| %>
  <% if movie_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_like.errors.count, "error") %> prohibited this movie_like from being saved:</h2>

      <ul>
      <% movie_like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie %>
    <%= f.number_field :movie %>
  </div>

  <div class="field">
    <%= f.label :like %>
    <%= f.check_box :like %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsimplementation/app/views/movie_likes/edit.html.erb
<h1>Editing Movie Like</h1>

<%= render 'form', movie_like: @movie_like %>

<%= link_to 'Show', @movie_like %> |
<%= link_to 'Back', movie_likes_path %>

railsimplementation/app/views/movie_likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Likes</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_likes.each do |movie_like| %>
      <tr>
        <td><%= movie_like.movie %></td>
        <td><%= movie_like.like %></td>
        <td><%= link_to 'Show', movie_like %></td>
        <td><%= link_to 'Edit', edit_movie_like_path(movie_like) %></td>
        <td><%= link_to 'Destroy', movie_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Like', new_movie_like_path %>

railsimplementation/app/views/movie_likes/new.html.erb
<h1>New Movie Like</h1>

<%= render 'form', movie_like: @movie_like %>

<%= link_to 'Back', movie_likes_path %>

railsimplementation/app/views/movie_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @movie_like.movie %>
</p>

<p>
  <strong>Like:</strong>
  <%= @movie_like.like %>
</p>

<%= link_to 'Edit', edit_movie_like_path(@movie_like) %> |
<%= link_to 'Back', movie_likes_path %>